# Generated by Django 6.1.1 on 2026-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_totp_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='espees_wallet_address',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='wallet',
            name='external_account_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='wallet',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wallet',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='status_detail',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('requested', 'Requested'), ('provisioning', 'Provisioning'), ('associated', 'Associated'), ('pending_external', 'Pending external (awaiting Espees)'), ('requires_action', 'Requires action'), ('failed', 'Provisioning failed'), ('pending', 'Pending provisioning (legacy)'), ('active', 'Active (legacy)')], default='not_started', max_length=16),
        ),
    ]
