# Generated by Django 6.1.1 on 2026-09-21 18:04

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='business-covers/', validators=[core.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business-logos/', validators=[core.validators.validate_image_size]),
        ),
    ]
