# Generated by Django 6.1.1 on 2026-09-20 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('commerce', '0001_initial'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='campaigns.campaign'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['initiator', 'campaign'], name='conversatio_initiat_454fde_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['other_party', 'campaign'], name='conversatio_other_p_95424c_idx'),
        ),
    ]
