# Generated by Django 6.1.1 on 2026-09-20 19:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_espees', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_requests', to='businesses.category')),
                ('requesting_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_requests', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_espees', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='submitted', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='businesses.business')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.supplierrequest')),
            ],
            options={
                'ordering': ['amount_espees'],
            },
        ),
        migrations.AddIndex(
            model_name='supplierrequest',
            index=models.Index(fields=['status', 'created_at'], name='quotes_supp_status_5a82c0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierrequest',
            index=models.Index(fields=['category', 'status'], name='quotes_supp_categor_8729e5_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['request', 'status'], name='quotes_quot_request_e9d29d_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['supplier_business'], name='quotes_quot_supplie_ac6900_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('request', 'supplier_business'), name='unique_quote_per_request_supplier'),
        ),
    ]
