# Generated by Django 6.1.1 on 2026-09-21 18:04

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offerings/', validators=[core.validators.validate_image_size]),
        ),
    ]
