# Generated by Django 6.1.1 on 2026-09-20 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='businesses.business')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='commerce.offering')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business'], name='reviews_rev_busines_f0b9cf_idx'), models.Index(fields=['offering'], name='reviews_rev_offerin_935cbd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('business__isnull', False), ('offering__isnull', False), _connector='OR'), name='review_has_target'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range'), models.UniqueConstraint(condition=models.Q(('business__isnull', False)), fields=('reviewer', 'business'), name='unique_reviewer_business'), models.UniqueConstraint(condition=models.Q(('offering__isnull', False)), fields=('reviewer', 'offering'), name='unique_reviewer_offering')],
            },
        ),
    ]
