# Generated by Django 6.1.1 on 2026-09-22 12:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('merchant_payment', 'Merchant payment')], default='merchant_payment', max_length=32)),
                ('product_sku', models.CharField(max_length=64)),
                ('narration', models.CharField(max_length=255)),
                ('amount_espees', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('merchant_wallet', models.CharField(max_length=128)),
                ('success_url', models.CharField(blank=True, default='', max_length=512)),
                ('fail_url', models.CharField(blank=True, default='', max_length=512)),
                ('user_data', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('espees_payment_ref', models.CharField(blank=True, default='', max_length=128)),
                ('external_status', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('requires_reconciliation', 'Requires reconciliation')], default='initiated', max_length=24)),
                ('status_detail', models.CharField(blank=True, default='', max_length=512)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eenp_transaction_id', models.CharField(max_length=64)),
                ('external_reference', models.CharField(blank=True, default='', max_length=128)),
                ('operation_type', models.CharField(default='merchant_payment', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='ESP', max_length=8)),
                ('external_status', models.CharField(blank=True, default='', max_length=32)),
                ('internal_status', models.CharField(blank=True, default='', max_length=24)),
                ('reconciliation_status', models.CharField(choices=[('matched', 'Matched'), ('pending', 'Pending'), ('mismatched', 'Mismatched'), ('missing_external', 'Missing external'), ('missing_platform', 'Missing platform'), ('unknown', 'Unknown')], default='pending', max_length=24)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_records', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['initiator', 'created_at'], name='payments_pa_initiat_97ca7c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['espees_payment_ref'], name='payments_pa_espees__27212d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['eenp_transaction_id'], name='payments_re_eenp_tr_ee05b9_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['external_reference'], name='payments_re_externa_6093d9_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['reconciliation_status', 'created_at'], name='payments_re_reconci_799d95_idx'),
        ),
    ]
