# Generated by Django 6.1.1 on 2026-09-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='status_details',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_date_raw',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
